# Done to increase the memory available to gradle.
    org.gradle.jvmargs=-Xmx3G
    org.gradle.parallel=true
# com.github.hierynomus.license 0.16.1 accesses Task.project at execution time.
# That task is incompatible with Gradle's configuration cache.
    org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
    minecraft_version=26.3
    loader_name=fabric
    loader_version=0.19.5
    loom_version=1.18-SNAPSHOT

# Mod Properties
    version=1.0.0
    group=io.github.piscescup.fabricmc.carpetgui
    mod_id=carpet-gui
    mod_name=Carpet GUI
    archives_base_name=carpet-gui

# Dependencies
    fabric_api_version=0.161.0+26.3
    modmenu_version=21.0.0
    tcdcommons_version=FwE7UAgA
    carpet_version=26.3

# Test
    junit_version=6.1.3
