# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=1.21.11
	minecraft_version=1.21.11
	parchment_version=2025.12.20

# Fabric Mod Metadata
	minecraft_dependency=>=1.21.11 <1.22
	java_dependency=>=21
	carpet_dependency=>=1.4.194
	tcdcommons_dependency=>=5.1.0
	modmenu_dependency=>=17.0.1

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=1.21.11

# Dependencies
	fabric_api_version=0.141.6+1.21.11
	modmenu_version=17.0.1
	tcdcommons_version=X850L9UC
	carpet_version=1.4.194
