# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.3
	minecraft_version=26.3
	parchment_version=

# Fabric Mod Metadata
	minecraft_dependency=>=26.3 <26.4
	java_dependency=>=25
	carpet_dependency=>=26.3
	tcdcommons_dependency=>=5.6.0-beta.2
	modmenu_dependency=>=21.0.0

# Build Information
	# The target mc versions for the mod during mod publishing, separated with newline
	game_versions=26.3

# Dependencies
	fabric_api_version=0.162.0+26.3
	modmenu_version=21.0.0
	tcdcommons_version=FwE7UAgA
	carpet_version=26.3
